### PR TITLE
ci: fix tag

### PR DESCRIPTION
**Pull request by Jaryt**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:c5d377df9d2673524925ee4cfc7d59f8001b20c6

**Review by JalexChen — APPROVED** [review]
loving the changes

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:a60e0eea510e4e70e435b874f14c041df45d7730

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=1.0.0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:a60e0eea510e4e70e435b874f14c041df45d7730

**Pull request merged**
