### PR TITLE
Replace outdated argument with --public-key-id

### LINKED ISSUE #13: Attestation fails because --pgp-key-fingerprint is not a valid argument
The `--pgp-key-fingerprint` argument is no longer used by the GCP CLI, making builds fail:

https://github.com/CircleCI-Public/gcp-binary-authorization-orb/blob/d6e3ff50ad1a4bf1706f0f869c80074cc33b74a1/src/commands/create-attestation.yml#L257
```
ERROR: (gcloud.beta.container.binauthz.attestations.create) unrecognized arguments: --pgp-key-fingerprint=4E25EF3C8EA9CB5732ECFBB54643C84258CE89DC 

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

Exited with code exit status 2
CircleCI received exit code 2
```

### PR DESCRIPTION
**Pull request by otherguy**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Fixes #13 

### Description

Replace outdated `--pgp-key-fingerprint` argument with `--public-key-id`, according to current [`gcloud beta` documentation](https://cloud.google.com/sdk/gcloud/reference/beta/container/binauthz/attestations/create)

### CODE REVIEW

**Comment by Jaryt** [comment]
Hi, thank you for your patience. I'm getting this merged in now, but it seems that I'll need to update orb tools. I'll do that on this PR so that everything can get merged smoothly.

**Comment by Jaryt** [comment]
Created #15

**Comment by otherguy** [comment]
Thank you!

**Comment by otherguy** [comment]
@Jaryt any news on this?

**Comment by Jaryt** [comment]
> @Jaryt any news on this?

Hi! I am OOO this week. I only had a few changes to make for migrating the orb. I should be able to find a second to make those changes today.

**Comment by otherguy** [comment]
No worries, I’m OOO myself this week. Just wanted to ask :)

**Comment by Jaryt** [comment]
Hey @otherguy glad to hear this wasn't holding you up last week. I've completed another step of our orb tools migration, but more work is popping up after more is done. Will crack at it more tomorrow and update you once progress is made :) Thanks for your patience!

**Comment by Jaryt** [comment]
Hi @otherguy another update! Had a small permission bump but now I have access to the things to get this finished. Going to make sure this is in this week 😄

**Comment by otherguy** [comment]
Awesome! Looking forward to using this 😃  Thank you!

**Comment by Jaryt** [comment]
Hey! More updates. Found out this uses more projects that I need elevated privileges for. I'm making changes so that it doesn't have to be done this way for future maintenance, but unfortunately I'm getting caught up on these permission issues here and there. Seems like most of the orb itself is still functional with some bits here and there needing attention. 

Will keep you posted.

**Comment by otherguy** [comment]
Good to hear. Still waiting to use that ASAP :)

**Comment by Jaryt** [comment]
Hey @otherguy! So this turned out to be quite the rabbit hole. There is still an integration test to investigate, but I'm going to continue to chip at it. Also, I'll be upgrading to the GA version of bin auth, since the last time this orb has been updated.

Will close this PR out since the changes will be made according to the https://cloud.google.com/sdk/gcloud/reference/container/binauthz docs

**Pull request closed without merging**
