### PR TITLE
ci: fix integration tests

### PR DESCRIPTION
**Pull request by Jaryt**
All integration tests are now passing once again.

### CODE REVIEW

**Comment by Jaryt** [comment]
@otherguy Once this PR is merged, then a new version will be released! 🎉

**Comment by otherguy** [comment]
Awesome @Jaryt! 👏 Thank you so much! Looking forward!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:d6e6322110fe08ec327612e720abfdac4f1588d0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:d6e6322110fe08ec327612e720abfdac4f1588d0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:d6e6322110fe08ec327612e720abfdac4f1588d0

**Comment by Jaryt** [comment]
@otherguy v1.0.0 is released!

**Comment by otherguy** [comment]
@Jaryt awesome, thank you so much! We're already using it 😄

Much appreciated!

**Pull request merged**
