### PR TITLE
Feature: Dynamically evaluate IMAGE_PATH

### PR DESCRIPTION
**Pull request by otherguy**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

While the `image-tag` parameter value is dynamic and evaluated at runtime (allowing things like `image-tag: ${VERSION}`), the `image-path` parameter is not, requiring the Docker image path to be stored directly in the CircleCI `config.yaml`. 

In our specific case, the Docker image name is generated dynamically during CI runtime, which is impossible with the current implementation.

### Description

Add `eval` wrapper to every instance of `image-path`.

### CODE REVIEW

**Comment by otherguy** [comment]
@Jaryt unfortunately, the current version of the orb still can't be used with our CI pipelines because we dynamically generate Docker image names.

This PR should fix that.

**Review by Jaryt — APPROVED** [review]
Reasonable change. Merging in!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-binary-authorization?version=dev:6856176751dbe3eaf8c715bdfb2d58ba63a74b71

**Comment by otherguy** [comment]
Awesome, thanks @Jaryt! I just tried the development version above and can confirm it's working.

Could you please create a release so we can continue to use this after the development version expires in 30 days 😉

**Comment by Jaryt** [comment]
> Awesome, thanks @Jaryt! I just tried the development version above and can confirm it's working.

Very welcome! Thanks for confirming :)

> Could you please create a release so we can continue to use this after the development version expires in 30 days 😉

There are still some attestor integration tests failing. I'm working on getting them up and running now. Once those are passing I'll cut a new release. I'm going to do my best to get this done today!

**Comment by Jaryt** [comment]
@otherguy phew, almost done here. Got past a number of issues but hit one more snag. Will return to this and get a release out Monday!

**Pull request merged**
